# Container definitions for development

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql

  # # Optional phpmyadmin container for database monitoring and troubleshooting
  # phpmyadmin:
  #   image: phpmyadmin:latest
  #   container_name: phpmyadmin
  #   ports:
  #     - "8040:80"
  #   environment:
  #     PMA_HOST: mysql
  #     MYSQL_ROOT_PASSWORD: root_password
  #   restart: unless-stopped

  backend:
    image: gradle:latest
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/home/gradle/project
      - gradle_cache:/home/gradle/.gradle
    working_dir: /home/gradle/project
    environment:
      DB_URL: jdbc:mysql://mysql:3306/tmp?createDatabaseIfNotExist=true
      DB_USERNAME: root
      DB_PASSWORD: root_password
    command: gradle bootRun
    depends_on:
      - mysql
    restart: unless-stopped

  frontend:
    image: node:latest
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm run host"
    restart: unless-stopped

volumes:
  mysql_data:
  gradle_cache:
